language: python
python:
- '3.6'
install:
- pip install -r requirements/base.txt
script:
- make tests
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: davydany
  password:
    secure: zVG+STtgUI1dYJlq5JFUFXGQRz9AMkhHC6C/Vo410GxLttm3NKiDPMt/kPzNcPFx20qUDH6sHMiHGc8Xj+g5nJf0eVtup+Q8TidHqrL8E3wFGvr94nvyM0x6ILJypozFCUOsKC/faet7tHybs3u0iH5jiUCsmuakUDlG+oEh2FNkDp/5pymxAkgR5MHOdwXLvyLXZgK7Kq9MqARxlDs50cs+J+L6DzVhapSIAtIS4Ss7WXTQVF5mQFJ1I7rgHe6oMZZyvi+LoRDcmTUlt81mvXx1RXKI5RtsqYCVN5Pwo8jvEPDnvP7zZPs2gc6DprkIjvVarQiMt4qSVYrCIBpVvPAWTQHsvCwy5GYcs0v8xWi3+fNdrJ2oDoL7zQhb7IEa+X3y8OXDf+xCbbxhhM80LvfXUQq6Q1yDjw3jTB7sZ8aC1b0VCm03sCB1vFaBi4nbTv70y9F1F/58e8BLsY+g0az68Kk/QVbcsR3Txs3jai/T/fxBKhVISoDrkjPLGPE9W2eehVNi6VEKowEfXKECNHv4RzuzJ9E6pOaJYBQMRFTr2HPKpgpWMb2Cqbx6IA8aIAwkfo5livuOzTjnMGiWBKZqcWdYdmtBAlAUcIOJzqAmAeMLUYhK48hFv021l6mbqtBmNiek6JH7vHZrrfMWfTv1Gk3ebukXdFKzE+IjzBM=
  on:
    repo: aeroxis/gypse
    branch: master
